version: '2'

# Service definition for Consul cluster with a minimum of 3 nodes.
# For local development we use Compose v2 so that we have an automatically
# created user-defined network and internal DNS for the name "consul".
# Nodes will use Docker DNS for the service (passed in via the CONSUL
# env var) to find each other and bootstrap the cluster.
services:
  daas:
    build: .
    restart: always
    mem_limit: 128m
    ports:
      - 88
      - 389
      - 464
      - 749
    dns:
      - 127.0.0.1
    domainname: node.zeroae
    depends_on:
      - consul
    env_file:
      - .env
    environment:
      - CONSUL=consul
      - CONSUL_DOMAIN=zeroae
      - KRB5_ADMIN_PASSWORD=admin_password
      - LDAP_ORGANIZATION=ZeroAE LLC

  consul:
    image: zeroae/ap-consul
    restart: always
    mem_limit: 128m
    ports:
      - 8500
    dns:
      - 127.0.0.1
    domainname: node.zeroae
    environment:
      - CONSUL=consul
      - CONSUL_DOMAIN=zeroae
      - CONSUL_BOOTSTRAP_EXPECT=1
